stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - docker
  image: docker
  before_script:
    - apk add --no-cache py3-pip python3-dev libffi-dev openssl-dev curl gcc libc-dev make
    - pip3 install docker-compose
  script:
    - docker context create remote --docker "host=tcp://$REMOTE_DOCKER_HOST:$REMOTE_DOCKER_PORT"
    - docker context use remote
    - docker context use default
    - docker-compose --context remote up -d --build
