version: '3.1'

services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      MONGO_DATABASE_URI: ${MONGO_DATABASE_URI}
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
      API_ID: ${API_ID}
      SECRET: ${SECRET}
      SESSION_PATH: ${SESSION_PATH}
    links:
      - mongo
    restart: always
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_storage:/data/db

volumes:
  mongo_storage: {}